services:
  app:
    container_name: sva_app
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - svanetwork
    depends_on:
      - redis-stack

  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: sva_redis
    ports:
      - "6379:6379"
    networks:
      - svanetwork

  qdrant:
    image: qdrant/qdrant:latest
    container_name: sva_qdrant
    ports:
      - "6333:6333"
    networks:
      - svanetwork

networks:
  svanetwork:
    external: true
