from fastapi import APIRouter, Depends
from fastapi.responses import JSONResponse
from app.models.requests import SuggestionsRequest
from app.utils import get_cache
from app.auth.jwt_auth import get_current_user
from helpers.translation import BhashiniTranslator
import asyncio

router = APIRouter(prefix="/suggest", tags=["suggest"],)

# NOTE: No need for rate limiting here as it's invoked by the chat method only.
@router.get("/")
async def suggest(request: SuggestionsRequest = Depends(), user_info: dict = Depends(get_current_user)):
    """
    Get suggestions for a conversation session.
    Polls cache until suggestions are generated by the background task (up to 35s).
    """
    # Bhili UI uses bhb; suggestions are generated in mr (see chat flow), then mr → bhb here.
    cache_lang = "mr" if request.target_lang == "bhb" else request.target_lang
    cache_key = f"suggestions_{request.session_id}_{cache_lang}"

    # Poll for up to 35 seconds (70 * 0.5s) waiting for background task to write suggestions.
    # get_cache returns None on cache miss, so None means "not ready yet".
    suggestions = None
    for _ in range(70):
        suggestions = await get_cache(cache_key)
        if suggestions is not None:
            break
        await asyncio.sleep(0.5)

    suggestions = suggestions or []
    if request.target_lang == "bhb" and suggestions:
        translator = BhashiniTranslator(source_lang="mr", target_lang="bhb")
        suggestions = await translator.translate(suggestions)
    return JSONResponse(suggestions)